---

- name: "config: Create directories for Ansible Lint configuration"
  ansible.builtin.file:
    state: directory
    dest: "{{ item.path|dirname }}"
    mode: "{{ item.dir_mode|default('0700') }}"
  loop: "{{ mal_config }}"
  loop_control:
    label: "{{ item.path|dirname }}"

- name: "config: Configure Ansible Lint"
  ansible.builtin.template:
    src: "{{ item.template|default('ansible-lint-default.j2') }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "{{ mal_backup_conf }}"
  loop: "{{ mal_config }}"
  loop_control:
    label: "{{ item.path }}"

# EOF
...
