---

- name: Create directories for links
  block:

    - name: "Links: Create directories for links"
      register: result
      ansible.builtin.file:
        state: directory
        dest: "{{ item.dest | dirname }}"
        mode: "{{ item.dir_mode | d('0755') }}"
      loop: "{{ mal_links }}"
      loop_control:
        label: "{{ item.dest | dirname }}"

  rescue:

    - name: "Links: Rescue create directories for links"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

- name: Create links
  block:

    - name: "Links: Create links"
      register: result
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: "{{ item.force | d(false) }}"
      loop: "{{ mal_links }}"

  rescue:

    - name: "Links: Rescue create links"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

# EOF
