---
# tasks for ansible_lint

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [mal_vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: mal_debug|bool
  tags: mal_debug

- name: Import sanity.yml
  ansible.builtin.import_tasks: sanity.yml
  when: mal_sanity|bool
  tags: mal_sanity

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: mal_pkg_install|bool
  tags: mal_packages

- name: Import pip.yml
  ansible.builtin.import_tasks: pip.yml
  when: mal_pip_install|bool
  tags: mal_pip

- name: Import source.yml
  ansible.builtin.import_tasks: source.yml
  when: mal_source_install|bool
  tags: mal_source

- name: Import links.yml
  ansible.builtin.import_tasks: links.yml
  tags: mal_links

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml
  tags: mal_config

# EOF
...
