---

# TODO: Still open?
# pip module always set to changed when using check mode #62826
# https://github.com/ansible/ansible/issues/62826
- name: "pip: Debug check mode"
  ansible.builtin.debug:
    msg: Module pip does not support check mode. Skipping.
  when: ansible_check_mode

- name: "pip: Install Ansible Lint pip packages for {{ mal_owner }}"
  block:
    - name: "pip: Install Ansible Lint pip packages for {{ mal_owner }}"
      become_user: "{{ mal_owner }}"
      become: true
      ansible.builtin.pip:
        name: "{{ item.name }}"
        executable: "{{ mal_pip_executable }}"
        extra_args: "{{ mal_pip_extraagrs|default(omit) }}"
        version: "{{ item.version|default(omit) }}"
        state: "{{ item.state|default(omit) }}"
      loop: "{{ mal_packages }}"
      register: result
      until: result is succeeded
      retries: "{{ pip_install_retries }}"
      delay: "{{ pip_install_delay }}"
    - name: "pip: Debug pip packages"
      ansible.builtin.debug:
        var: result
      when: mal_debug|bool
  rescue:
    - name: "pip: Rescue pip packages"
      ansible.builtin.fail:
        msg: |
          [ERROR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task|to_yaml(indent=2)|indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result|to_yaml(indent=2)|indent(2) }}
  when: not ansible_check_mode

- name: "pip: Install Ansible Lint pip requirements for {{ mal_owner }}"
  block:
    - name: "pip: Install Ansible Lint pip requirements for {{ mal_owner }}"
      become_user: "{{ mal_owner }}"
      become: true
      ansible.builtin.pip:
        requirements: "{{ mal_pip_requirements }}"
        executable: "{{ mal_pip_executable }}"
        extra_args: "{{ pip_extraagrs|default(omit) }}"
      loop: "{{ mal_pip_requirements }}"
      register: result
      until: result is succeeded
      retries: "{{ pip_install_retries }}"
      delay: "{{ pip_install_delay }}"
      when: mal_pip_requirements|length > 0
    - name: "pip: Debug pip requirements"
      ansible.builtin.debug:
        var: result
      when: mal_debug|bool
  rescue:
    - name: "pip: Rescue pip requirements"
      ansible.builtin.fail:
        msg: |
          [ERROR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task|to_yaml(indent=2)|indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result|to_yaml(indent=2)|indent(2) }}
  when: not ansible_check_mode

# EOF
...
