---
- name: Declare mal_owner when undefined
  when: mal_owner is undefined

  block:
    - name: "Vars: Get the user"
      ansible.builtin.setup:
        gather_subset: user
      become: false

    - name: "Vars: Debug user"
      ansible.builtin.debug:
        msg: |
          ansible_user: {{ ansible_user | d('UDEFINED') }}
          ansible_user_id: {{ ansible_user_id | d('UDEFINED') }}
      when: mal_debug|bool

    - name: "Vars: Declare mal_owner"
      ansible.builtin.set_fact:
        mal_owner: "{{ ansible_user | d(ansible_user_id) }}"

- name: "Vars: Include OS vars"
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_include_os_vars_path
  vars:
    al_os_vars_path: "{{ ansible_parent_role_paths.0 }}" # noqa: var-naming[no-role-prefix]

- name: "Vars: Override mal_packages"
  ansible.builtin.set_fact:
    mal_packages: "{{ mal_packages_override }}"
  when: mal_packages_override is defined

- name: "Vars: Override mal_pip_executable"
  ansible.builtin.set_fact:
    mal_pip_executable: "{{ mal_pip_executable_override }}"
  when: mal_pip_executable_override is defined

- name: "Vars: Override mal_pip_requirements"
  ansible.builtin.set_fact:
    mal_pip_requirements: "{{ mal_pip_requirements_override }}"
  when: mal_pip_requirements_override is defined

# EOF
