---

- name: "Venv: Install packages for Python virtual environment."
  when: mal_virtualenv_packages | length > 0
  vars:
    mal_packages_incl: "{{ mal_virtualenv_packages }}"
  ansible.builtin.include_tasks: fn/packages.yml

- name: Install Ansible Lint PyPI packages for mal_owner
  block:

    - name: "Venv: Install Ansible Lint PyPI packages for {{ mal_owner }}"
      become_user: "{{ mal_owner }}"
      become: true
      register: result
      # changed_when: result.changed
      ansible.builtin.pip:
        name: "{{ item.name }}"
        # executable: "{{ mal_pip_executable }}"
        # extra_args: "{{ mal_pip_extraagrs | d(omit) }}"
        version: "{{ item.version | d(omit) }}"
        state: "{{ item.state | d(omit) }}"
        virtualenv: "{{ mal_virtualenv }}"
        virtualenv_command: "{{ mal_virtualenv_command | d(omit) }}"
        virtualenv_python: "{{ mal_virtualenv_python | d(omit) }}"
        virtualenv_site_packages: "{{ mal_virtualenv_site_packages | d(omit) }}"
      loop: "{{ mal_pip_packages }}"
      until: result is succeeded
      retries: "{{ pip_install_retries }}"
      delay: "{{ pip_install_delay }}"

    - name: "Venv: Debug PyPI packages mal_debug={{ mal_debug }}"
      when: mal_debug | bool
      ansible.builtin.debug:
        var: result

  rescue:

    - name: "Venv: Rescue PyPI packages"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

# EOF
