---

- name: FreeBSD packages
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method | lower == 'packages'
  block:

    - name: "Packages: Install Ansible Lint FreeBSD packages"
      community.general.pkgng:
        name: "{{ item.name }}"
        state: "{{ item.state | d(omit) }}"
      loop: "{{ mal_packages_incl }}"
      register: result
      until: result is succeeded
      retries: "{{ freebsd_install_retries }}"
      delay: "{{ freebsd_install_delay }}"

    - name: "Packages: Debug FreeBSD packages mal_debug={{ mal_debug }}"
      when: mal_debug | bool
      ansible.builtin.debug:
        var: result

  rescue:

    - name: "Packages: Rescue FreeBSD packages"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

- name: FreeBSD ports
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method | lower == 'ports'
  block:

    - name: "Packages: Install Ansible Lint FreeBSD ports"
      register: result
      community.general.portinstall:
        name: "{{ item.name }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ mal_packages_incl }}"
      until: result is succeeded
      retries: "{{ freebsd_install_retries }}"
      delay: "{{ freebsd_install_delay }}"

    - name: "Packages: Debug FreeBSD ports mal_debug={{ mal_debug }}"
      when: mal_debug | bool
      ansible.builtin.debug:
        var: result

  rescue:

    - name: "Packages: Rescue FreeBSD ports"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

- name: Linux packages
  when: ansible_os_family in mal_supported_linux_family
  block:

    - name: "Packages: Install Ansible Lint Linux packages"
      register: result
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state | d(omit) }}"
      loop: "{{ mal_packages_incl }}"
      until: result is succeeded
      retries: "{{ linux_install_retries }}"
      delay: "{{ linux_install_delay }}"

    - name: "Packages: Debug Linux packages mal_debug={{ mal_debug }}"
      when: mal_debug | bool
      ansible.builtin.debug:
        var: result

  rescue:

    - name: "Packages: Rescue Linux packages"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

# EOF
